#int() used to convert in  integer  33.14=int=3
# print(int(3.14))
# print(int(10+5))
# print(int(True))
# print(int(False))
# #print(int("4,22"))
# print(int("4"))
# print(int("tirthenmdu"))

# print(float(3.14))
# print(float(10+5))
# print(float(True))
# print(float(False))
# print(float("4.22"))
# print(float("4"))
# print(float("tirthenmdu"))

# print(complex(3.14))
# print(complex(10+5))
# print(complex(True))
# print(complex(False))
# print(complex("4.22"))
# print(complex("4"))
# #print(complex("tirthenmdu"))
# print(complex(5,-3))
# print(complex(True,False))

# print(bool(3.14))
# print(bool(10+5))
# print(bool(True))
# print(bool(False))
# print(bool("4,22"))
# print(bool("4"))
# print(bool("tirthenmdu"))
print(bool(-1))
print(bool(1+2j))
print(bool(0+0j))
print(bool(False))
print(bool(""))
